SITES:
  - NAME : Sonarr
    port : http://localhost:8989/
    cover : sonarr.png
  - NAME : Radarr
    port : http://localhost:7878/
    cover : radarr.png
  - NAME : Prowlarr
    port : http://localhost:9696/
    cover : prowlarr.png
  - NAME : Jelly
    port : http://localhost:8096/
    cover : jelly.png
  - NAME : Stash
    port : http://localhost:9999/
    cover : stash.png
